Release and update en
KPI-IP94-Database/TeamOne pull request #5
Opened 2020-09-22 08:13 UTC by vladlinu

2020-09-22 08:16 UTC, Koroliuk approved these changes
Добре

2020-09-22 08:27 UTC, Koroliuk commented
Додай пусті рядки в змістові як в україномовному документі

2020-09-22 08:34 UTC, Koroliuk approved these changes

2020-10-04 17:44 UTC, Koroliuk commented
Додай ще можливість реєстрації для неавторизованого користувача

2020-10-04 18:19 UTC, vladlinu reviewed
Log in to existing account добавлено

2020-10-04 18:26 UTC, vladlinu commented
регистрация добавлена

2020-10-04 18:28 UTC, vladlinu reviewed
все сделано

2020-10-07 19:58 UTC, Koroliuk approved these changes

2020-10-07 19:58 UTC, Koroliuk commented
Все добре

2020-10-12 08:49 UTC, Proxima-C approved these changes
Ok 👍

2020-10-12 17:36 UTC, vladlinu commented
Uml activity diagrams for unauthorized user functions

2020-10-15 14:53 UTC, vladlinu commented
конфликта нету

2020-10-15 18:35 UTC, Koroliuk commented on docs/stakeholdersUA.md
> +* можливість реєстрації облікового запису
```suggestion
* можливість авторизації;
* можливість реєстрації облікового запису.
```

2020-10-17 10:50 UTC, a-mountain requested changes
Pull request name is not corresponding his content

2020-10-17 14:37 UTC, a-mountain approved these changes

2020-10-17 15:52 UTC, a-mountain requested changes
I am not sure that user should have permission to registration by himself. That needs discuss.

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-1.pu
> +<font color=000 size=16><b>Результат:</b> Користувач залогінився в системі.
залогінився is not suitable word for official document

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-1.pu
> +@enduml
Newline must be at the end of file

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-2.pu
> +@enduml
Newline must be at the end of file

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-2.svg
> +--></g></svg>
Newline must be at the end of file

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-3.pu
> +@enduml
Newline must be at the end of file

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-3.svg
> +--></g></svg>
Newline must be at the end of file

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-4.pu
> +@enduml
Newline must be at the end of file

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-4.pu
> +<font color=000 size=16> E_05: Введені невірні дані
"Введені невірні дані" is not accurate name for this exception. It's better to use "Користувач вже існує"

2020-10-17 15:52 UTC, a-mountain commented on UML_Diagrams/unauthorized_user/UC-4.pu
> +: Користувач зареєстрований і може залогінитися;
"залогінитися" is not suitable name for this document. It's better to use "авторизуватися"

2020-10-17 18:50 UTC, vladlinu commented on UML_Diagrams/unauthorized_user/UC-4.pu
> +<font color=000 size=16> E_05: Введені невірні дані
Здесь имеется в виду что такого студента не существует, поэтому неверные данные

2020-10-18 20:02 UTC, Koroliuk commented on UML_Diagrams/unauthorized_user/UC-3.pu
> +: Користувач вводить ім'я та фамілію викладача;
Чи не міг би ти замінити "фамілія" на "прізвище"

2020-10-18 20:05 UTC, Koroliuk commented on UML_Diagrams/unauthorized_user/UC-3.pu
> +: Система перевіряє наявність викладача із вказаним ім'ям;
Чи не міг би ти замінити "ім'ям" на "ім'ям та прізвищем" або на "даними"

2020-10-18 20:51 UTC, Pienskoi commented on UML_Diagrams/unauthorized_user/UC-1.pu
> +Системна динаміка. Модель прецендентів.
Change "Системна динаміка" in all files to our project name "Система контролю навчання" or "Education Control System".

2020-10-19 14:11 UTC, closed without merging